name: master

on:
  push:
    branches:
      - master

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Lint
        uses: actions-contrib/golangci-lint@master
      - name: Build project # This would actually build your project, using zip for an example artifact
        run: |
          make